config/routes.rb
Betterplace::Application.routes.draw do
  get "pages/home"

  root 'pages#home'

  get "pages/about"
  get "pages/options"
  get "pages/faq"
  get "pages/thanks"
  

  resources :contacts, only: [:new, :create]
  post 'new_contact' => 'contacts#create'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(contact_params)
  	@option = params[:contact][:option]
    @name = params[:contact][:name]
    @email = params[:contact][:email]
    @phone = params[:contact][:phone]
    @comments = params[:contact][:comments]
    
  	if @contact.save
      ContactMailer.notify_sales(@name, @option, @email, @phone, @comments).deliver
  	  redirect_to pages_thanks_path
  	else
  		render new_contact_path
  		flash[:notice] = "Oops. Please enter the correct information and try again."
  	end
  end

  private

  def contact_params
  	params.require(:contact).permit(:option, :name, :phone, :email, :comments)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def options
  end

  def faq
  end

  def thanks
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
 <%= render 'layouts/navigation' %>
   <section class="contact_background section section-on-bg">
        <div class="container text-center">                
           
           
        </div><!--//container-->
    </section><!--//promo-->
        
        <!-- ******Contact Section****** --> 
        <section class="contact-section section section-on-bg mobile-contact-header contact_offset">
            <div class="container">

                <h2 class="title contact_header" style="text-align:center;"><span style="font-size: 46px; font-weight: 700; text-shadow: 0 1px 1px rgba(0, 0, 0, 0.5);">We’d Love to Hear From You</span></h2>
                

                 <%= form_for @contact, url: contacts_path, html: { class: "contact-form"} do |f| %>               
                    <div class="row text-center">
                        <div class="contact-form-inner col-md-8 col-sm-12 col-xs-12 col-md-offset-2 col-sm-offset-0 xs-offset-0">
                            <div class="row">

                          
                            <%= render 'layouts/messages' %>
                           

                             <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                <h4>Choose your option below</h4>
                              <%= f.label :option, class: 'sr-only' %>
                              <%= f.select :option, options_for_select(["I would like Better Place for myself", "I would like Better Place for my loved one's ashes", "I operate a funeral home and would like to know more"]), {}, multiple: false, class: "form-control" %><br />
                              </div>
                              <div>
                                <h4>Please provide us with some details</h4>
                            </div>

                              <div class="col-md-6 col-sm-6 col-xs-12 form-group">

                              <%= f.label :name, class: 'sr-only' %>
                              <%= f.text_field :name, placeholder: "Your name", class: 'form-control', style: "height: 40px;" %><br />
                              </div>

                              <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                              <%= f.label :email, class: 'sr-only' %>
                              <%= f.text_field :email, placeholder: "Your email", class: 'form-control', style: "height: 40px;" %><br />
                              </div>

                              <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                              <%= f.label :phone, class: 'sr-only' %>
                              <%= f.text_field :phone, placeholder: "Your phone", class: 'form-control', style: "height: 40px;" %><br />
                              </div>

                              <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                <%= f.label :comments, class: 'sr-only' %>
                                <%= f.text_area :comments, placeholder: "Enter any comments or questions here", class: "form-control",:rows => "6" %>
                                </div>

                                 <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <%= f.submit 'Submit Details', class: 'btn btn-block btn-cta btn-cta-primary', style: "font-size: 24px; text-shadow: none !important;" %>
                                </div>  
                            <% end %>
                                          
                            </div><!--//row-->
                        </div>
                    </div><!--//row-->
                    <div id="form-messages"></div>
                </form><!--//contact-form-->
            </div><!--//container-->
        </section><!--//contact-section-->
        
        <!-- ******Other Contact Section****** --> 
        <section class="contact-other-section section">
            <div class="container text-center">
                <h2 class="title">Other ways to reach us</h2>
                <p class="intro">You can also get in touch by phone or email at your convenience. </p>
                <div class="row">
                    <ul class=" list-unstyled col-md-6 col-sm-10 col-xs-12 col-md-offset-3 col-sm-offset-1 xs-offset-0" >
                        <li><a href="#">brad@betterplacerest.com</a></li>
                      
                        <li><a href="tel:+14164646426">416 464 6426</a></li>
                        <li>51 Wolseley Street <br /> Toronto, Ontario<br />M5T 1A4<br />Canada</li>
                    </ul>
                </div><!--//row-->
                <br /><br /><br /><br /><br />
            </div><!--//container-->
        </section><!--//contact-other-section-->



<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="footer-content">
            <div class="container">
               
                <div class="row has-divider">
                    <div class="footer-col download col-md-6 col-sm-12 col-xs-12">
                        <div class="footer-col-inner">
                            <h3 class="title">How can we help?</h3>
                            <ul class="list-unstyled download-list" style="margin-left: -5px;">
                                <li><a class="btn btn-ghost" href="/"><i class="fa fa-apple"></i><span class="text" style="text-shadow: none !important;">Home</span> </a></li>
                                <li><a class="btn btn-ghost" href="/contacts/new"><i class="fa fa-android"></i><span class="text" style="text-shadow: none !important;">Contact Us</span></a></li>
                                <li><a class="btn btn-ghost" href="/pages/about"><i class="fa fa-windows"></i><span class="text" style="text-shadow: none !important;">About</span></a></li>
                            </ul>
                        </div><!--//footer-col-inner-->
                    </div><!--//download-->
                    <div class="footer-col contact col-md-6 col-sm-12 col-xs-12">
                        <div class="footer-col-inner">
                            <h3 class="title">Contact us</h3>                          
                            <p class="adr clearfix">
                                <i class="fa fa-map-marker pull-left"></i>        
                                <span class="adr-group pull-left">       
                                    <span class="street-address">51 Wolselsey Street</span><br>
                                    <span class="region">Toronto, Ontario</span><br>
                                    <span class="postal-code">M5T 1A4</span><br>
                                    <span class="country-name">Canada</span>
                                </span>
                            </p>
                            <p class="tel" style="margin-left: -10px;"><i class="fa fa-phone"></i>416 464 6426</p>
                            <p class="email" style="margin-left: -10px;"><i class="fa fa-envelope-o"></i><a href="#">info@betterplacerest.com</a></p> 
                                              
                        </div><!--//footer-col-inner-->
                    </div><!--//contact-->
                </div>
            </div><!--//container-->
        </div><!--//footer-content-->
        <div class="bottom-bar">
            <div class="container">
                <small class="copyright">Copyright @ 2015 Better Place Inc.</small>                
            </div><!--//container-->
        </div><!--//bottom-bar-->
    </footer><!--//footer-->
    
  
    
   
 

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
    
        <nav class="main-nav header" role="navigation">
            <div class="container"> 
            <div class="navbar-header">
               <a href="/" class="pull-left;" style="margin-top: -5px;"><%= image_tag('bp_logo.png') %></a>  
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->

            </div><!--//navbar-header-->
            <div id="navbar-collapse" class="navbar-collapse collapse  navbar-right" style="margin-top:15px;">
                <ul class="nav navbar-nav">
                    <li class="<%= 'active' if current_page?(root_path) %> nav-item"><%= link_to "Home", root_path %></li>
                    <li class="<%= 'active' if current_page?(pages_about_path) %> nav-item"><%= link_to "About Us", pages_about_path %></li>
                    <li class="<%= 'active' if current_page?(pages_options_path) %> nav-item"><%= link_to "Options", pages_options_path %></li>
                    <!-- <li class="nav-item"><a href="pricing.html">Pricing</a></li>    -->             
                    <li class="<%= 'active' if current_page?(pages_faq_path) %> nav-item"><%= link_to "FAQ", pages_faq_path %></li>
                    <li class="nav-item nav-item-cta last"><%= link_to "Contact Us", new_contact_path, class: 'btn btn-cta btn-cta-secondary' %></li>
                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
                </div><!--//container-->
        </nav><!--//main-nav-->                     

app/views/layouts/_navigation_original.html.erb
<header id="header" class="header">  
    <div class="container">       
        <a href="/" style="padding-top: 5px;"><%= image_tag('bp_logo.png') %></a>
        <nav class="main-nav navbar-right" role="navigation">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->
            </div><!--//navbar-header-->
            <div id="navbar-collapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="<%= 'active' if current_page?(root_path) %> nav-item"><%= link_to "Home", root_path %></li>
                    <li class="<%= 'active' if current_page?(pages_about_path) %> nav-item"><%= link_to "About Us", pages_about_path %></li>
                    <li class="<%= 'active' if current_page?(pages_options_path) %> nav-item"><%= link_to "Options", pages_options_path %></li>
                    <!-- <li class="nav-item"><a href="pricing.html">Pricing</a></li>    -->             
                    <li class="<%= 'active' if current_page?(pages_faq_path) %> nav-item"><%= link_to "FAQ", pages_faq_path %></li>
                    <li class="nav-item nav-item-cta last"><%= link_to "Contact Us", new_contact_path, class: 'btn btn-cta btn-cta-secondary' %></li>
                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->                     
    </div><!--//container-->
</header><!--//header-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betterplace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>

  <% if Rails.env.production? %>
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+t+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("732918749");
    </script>
   <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
  <%= render 'layouts/navigation' %>

 <section class="about_background section section-on-bg">
        <div class="container text-center">                
           
           <h2 class="title about_header" style="margin-top: 70px;"><span style="font-size: 46px; font-weight: 700; text-shadow: 0 1px 1px rgba(0, 0, 0, 0.5);">The First Sustainable Alternative to Cemeteries</span></h2>
        </div><!--//container-->
    </section><!--//promo-->

 <!-- ******Video Section****** --> 
    <section class="story-section section section-on-bg">
       <container>
        <h2 class="title container text-center"><span style="color:#00661E; font-size: 44px;">About Better Place</span></h2>
    </container>
        <div class="story-container container text-center" style="margin-top: -40px !important;"> 
            <div class="story-container-inner" >                    
                <div class="about">
                    <p style="font-size: 17px;">Better Place was created with the idea that there needs to be more options for peoples' final resting places other than cemeteries and urns.</p> 
                    <p style="font-size: 17px;">We believe that people want affordable, sustainable and unique options when it comes to how their remains will spend eternity, regardless of their beliefs. With the world population growing rapidly and lack of suitable burial space a real issue, Better Place aims to let people spend eternity in some of the most beautiful places on earth, in completely natural habitats, as part of the soil from which a tree grows.</p>
                    <div style="margin-top: 40px; text-align: center;">
                        <h3 style="font-family:  'Bevan', sans-serif; font-size: 24px; color: #00661E;line-height: 1.4;">By choosing Better Place, you are selecting a better place to rest and helping to preserve the most beautiful and natural places on earth.</h3><br />
                         <h3 style="font-family:  'Bevan', sans-serif; font-size: 24px; color: #00661E;">Spend Eternity in a Better Place</h3>

                    </div>              
                </div><!--//about-->
               


<!--
             
                <div class="press-kit text-center">
                    <h3 class="title">Press Kit</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.</p>
                    <p>Please <a href="contact.html">contact us</a> if you need more materials.</p>
                    <a class="btn btn-cta btn-cta-secondary" href="#">Download Press Kit</a>
                </div>

            -->
        </div>
        </div>
  </section>

     <%= render 'layouts/footer' %>
    

app/views/pages/contact.html.erb
 <%= render 'layouts/navigation' %>

  <section class="contact_background section section-on-bg">
        <div class="container text-center">                
           
           
        </div><!--//container-->
    </section><!--//promo-->



        
        <!-- ******Contact Section****** --> 
        <section class="contact-section section section-on-bg mobile-contact-header" style="margin-top: -400px; ">
            <div class="container">
                <h1 class="title text-center">Contact Us</h2>
                <p class="intro text-center">We’d love to hear from you. </p>
                <form id="contact-form" class="contact-form" method="post" action="">                    
                    <div class="row text-center">
                        <div class="contact-form-inner col-md-8 col-sm-12 col-xs-12 col-md-offset-2 col-sm-offset-0 xs-offset-0">
                            <div class="row">                                                           
                                
                                <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                    <label class="sr-only" for="cname">Your name</label>
                                    <input type="text" class="form-control" id="cname" name="name" placeholder="Your name" minlength="2" required>
                                </div>                    
                                <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                    <label class="sr-only" for="cemail">Email address</label>
                                    <input type="email" class="form-control" id="cemail" name="email" placeholder="Your email address" required>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <label class="sr-only" for="cmessage">Your message</label>
                                    <textarea class="form-control" id="cmessage" name="message" placeholder="Enter your message" rows="12" required></textarea>
                                </div>
                                 <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <button type="submit" class="btn btn-block btn-cta btn-cta-primary">Send Message</button>
                                </div>                           
                            </div><!--//row-->
                        </div>
                    </div><!--//row-->
                    <div id="form-messages"></div>
                </form><!--//contact-form-->
            </div><!--//container-->
        </section><!--//contact-section-->
        
        <!-- ******Other Contact Section****** --> 
        <section class="contact-other-section section">
            <div class="container text-center">
                <h2 class="title">Other ways to reach us</h2>
                <p class="intro">You can also get in touch lorem ipsum dolor sit amet. Donec ut massa consequat, bibendum metus pellentesque, pellentesque arcu. </p>
                <div class="row">
                    <ul class="other-info list-unstyled col-md-6 col-sm-10 col-xs-12 col-md-offset-3 col-sm-offset-1 xs-offset-0" >
                        <li><i class="fa fa-envelope-o"></i><a href="#">hello@yourwebsite.com</a></li>
                        <li><i class="fa fa-twitter"></i><a href="https://twitter.com/3rdwave_media" target="_blank">@3rdwave_themes</a></li>
                        <li><i class="fa fa-phone"></i><a href="tel:+0800123456">0800 123 456</a></li>
                        <li><i class="fa fa-map-marker"></i>Queen Square <br /> 56 College Green Road<br />BS1 XR18<br />Bristol<br />UK</li>
                    </ul>
                </div><!--//row-->
            </div><!--//container-->
        </section><!--//contact-other-section-->



<%= render 'layouts/footer' %>

app/views/pages/faq.html.erb
  <%= render 'layouts/navigation' %>
  <section class="faq_background section section-on-bg">
        <div class="container text-center">                
             <h2 class="title faq_header" style="margin-top: 70px;"><span style="font-size: 46px; font-weight: 700; text-shadow: 0 1px 1px rgba(0, 0, 0, 0.5);">Frequently Asked Questions</span></h2>
           
        </div><!--//container-->
    </section><!--//promo-->
 <!-- ******BLOG****** -->         
        <div class="blog-entry-wrapper" > 
              <h2 class="title text-center" style="margin-bottom: 40px;"><span style="color: #00661E; font-weight: 300; font-size: 44px; ">Sustainable & Natural</span></h2>
            <!--
            <div class="blog-headline-bg">
            </div><!--//blog-headline-bg-->
            <div class="blog-entry">                 
                <article class="post">
                   

                    <div class="container">
                        <div class="row">
                            <div class="blog-entry-content col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1 col-xs-offset-0">

                                <h3 class="section-heading" style="text-align:center !important;">How do I know where my loved one's tree is planted?</h3>
                                
                                <p>We will record the GPS location and add a small GPS marker or memorial plaque to your tree. (Your choice.) </p>
                                
                                
                                <h3 class="section-heading" style="text-align:center !important;">Can I visit my loved one's tree?</h3>
                                
                                <p>Yes, but this depends on the location you select. Some of our locations will be untouched natural wilderness that is difficult to access, while other locations are accessible. </p>

                                <h3 class="section-heading" style="text-align:center !important;">How do I know your land will never be redeveloped? </h3>

                                <p>Each Better Place wilderness park is zoned as a cemetery and held in a permanent care and maintenance trust. The land can never be legally redeveloped or changed. </p>


                                <h3 class="section-heading" style="text-align:center !important;">Can I choose the type of tree? </h3>
                                
                                <p>Yes. We will offer a few options of trees that are native to the location you select. You can also choose whether you would like a newly planted tree or a mature tree. </p>

                                <h3 class="section-heading" style="text-align:center !important;">Can't I just plant my own tree in a park? </h3>
                                
                                <p>You can, but ashes have a high pH that is damaging to trees if they aren't carefully treated. Better Place also provides the peace of mind of knowing that your loved one's tree will be in permanently protected wilderness. </p>

                                <h3 class="section-heading" style="text-align:center !important;">How much does Better Place cost? </h3>
                                
                                <p style="margin-bottom: 40px;">Better Place pricing will depend on the locations that we end up selecting. Please share your email address and thoughts to let us know what locations and pricing you think are best for Better Place. </p>

                               


                               
                               
                                
                               
                        </div><!--//row-->
                    </div><!--//container-->                                               
                </article><!--//post-->                                      
            </div><!--//blog-entry-->
        </div><!--//blog-entry-wrapper-->  
    </div><!--//wrapper-->

      <%= render 'layouts/footer' %>

app/views/pages/thanks.html.erb
  <%= render 'layouts/navigation' %>
 <!--
    <div class="bg-slider-wrapper">
        <div class="flexslider bg-slider">
            <ul class="slides">
                <li class="slide slide-1"></li>
                <li class="slide slide-2"></li>
                <li class="slide slide-3"></li>
            </ul>
        </div>
    </div><!--//bg-slider-wrapper-->        
   
    <section class="promo section section-on-bg">
        <div class="container text-center">                
            <h2 class="title">Thanks!</h2>
            <p style="color: #ffffff; font-size: 22px;">We'll be in touch as soon as we can.</p> 
           
        </div><!--//container-->
    </section><!--//promo-->
    

        
        
        
        <!-- ******Press Section****** 
        <section class="section press">
            <div class="container text-center">
                <h2 class="title">Press Coverage</h2>
                <ul class="press-list list-inline row">
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"> <%= image_tag('press-1.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"> <%= image_tag('press-2.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4 xs-break"><a href="#"> <%= image_tag('press-3.png', class: "img-responsive") %></li>                   
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-4.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-5.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-6.png', class: "img-responsive") %></a></li>                    
                </ul>
                <ul class="press-list list-inline row last">
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-7.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-8.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4 xs-break"><a href="#"><%= image_tag('press-9.png', class: "img-responsive") %></a></li>                   
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-10.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-11.png', class: "img-responsive") %></a></li>
                    <li class="col-md-2 col-sm-2 col-xs-4"><a href="#"><%= image_tag('press-12.png', class: "img-responsive") %></a></li>                    
                </ul>
                
                <div class="press-lead text-center">
                     <h3 class="title">Have press inquires?</h3>
                     <p class="press-links"><a href="#">Download our press kit</a> or <a href="contact.html">Get in touch</a></p>
                </div>
               
            </div>
        </section>
        -->
        <!-- ******CTA Section****** -->
        <section id="cta-section" class="section cta-section text-center home-cta-section">
            <div class="container">
               <h2 class="title">Interested in Better Place for you or a friend?</h2>
               <p><a class="btn btn-cta btn-cta-primary" href="pages/options" target="_blank">See Options</a></p>
            </div><!--//container-->
        </section><!--//cta-section-->
        
    </div><!--//section-wrapper-->
    
    <%= render 'layouts/footer' %>